### ISSUE TITLE
401 Unauthorized on deploying

### ISSUE THREAD

**Issue by liquidz** [clojure-emacs/clojuredocs-export-edn#1]
Deploying operation seems failing recently.
I noticed that logs in CircleCI shows `401 Unauthorized` on deploying.

@bbatsov Could you confirm that secrets for `NETLIFY_PERSONAL_ACCESS_TOKEN` and `NETLIFY_SITE_ID` are valid?

**Comment by bbatsov** [comment]
@liquidz Where exactly should I check this?

**Comment by bbatsov** [comment]
I don't have anything here https://app.netlify.com/user/applications, but I guess that's normal as those tokes are supposed to be on a per-user basis.

**Comment by bbatsov** [comment]
I think I got it. Generated a personal token, replaced the old one with CircleCI with the new one and now it works. I'm guessing only the owner of the team has deployment access on the basic plan. I don't know.

**Comment by liquidz** [comment]
Sorry for the lack of explanation.

> Generated a personal token, replaced the old one with CircleCI with the new one and now it works.

Great!

>  I'm guessing only the owner of the team has deployment access on the basic plan. I don't know.

It may be that the old personal token (it's mine) just happened to be able to deploy during a certain period of time after transferring.

Anyways, thanks so much!
