### ISSUE TITLE
export.compact.edn: Not found

### ISSUE THREAD

**Issue by bennyandresen** [clojure-emacs/clojuredocs-export-edn#5]
I just tried the refresh-cache command in cider and I get a FileNotFoundException.

Manually looking up the URL https://clojuredocs-edn.netlify.app/export.compact.edn with Firefox I get greeted by this:
Not found - Request ID: b2c6d382-98a3-4f32-a3c3-69bbf567e207-164746089

I'm not behind any proxy or anything that would hinder a Network request from within Emacs / the jvm.

**Comment by bbatsov** [comment]
We've killed the old Netlify app a while ago and these days the exports are retrieved from https://github.com/clojure-emacs/clojuredocs-export-edn/blob/master/exports/export.compact.edn Sorry that I missed your report when you made it!
